stages:
    - Build
    - Deploy

variables:
    VERBOSE: "1"
    MSBUILDDISABLENODEREUSE: "1"

Build Sample:
    stage: Build
    tags:
        - unity
        - windows
    script:
        - echo "$pwd"
        # correct syntax appears to be either:
        # double backslash in double quotes, or single backslash without quotes
        - $env:Path += ";C:\\Program Files\\Unity\\Editor"
        - echo $env:Path
        - $global:BuildFolder="FoveUnitySample"
        - mkdir $global:BuildFolder
        - cmd.exe /c "buildPlayer.bat $env:UNITY_CI_SERIAL $env:UNITY_CI_USERNAME $env:UNITY_CI_PASSWORD $global:BuildFolder/UnitySampleBuild.exe"
    artifacts:
        name: "FoveUnitySample"
        expire_in: 1 week
        paths:
            - FoveUnitySample/*
            
Deploy on NAS:
    stage: Deploy
    tags:
        - fove
        - linux
        - docker
    dependencies:
        - Build Sample
    script:
        - find .
        - export EXE_ZIP_NAME="FoveUnitySample"
        - zip -r "$EXE_ZIP_NAME.zip" "$EXE_ZIP_NAME"
        - export TODAY=`date +%Y_%m_%d-%H_%M_%S`
        - cp "$EXE_ZIP_NAME.zip" $FOVE_DATASETS/Random/CI_Builds/FoveUnitySample/$TODAY-$CI_PIPELINE_ID-$EXE_ZIP_NAME.zip

